### PR TITLE
Bug 2038419: Bump grafana to v8.3.3

### PR DESCRIPTION
**Pull request by arajkumar**
The merge/rebase process is based out of https://github.com/openshift/kubernetes/blob/master/REBASE.openshift.md#creating-a-new-local-branch-for-the-new-rebase

```
git checkout -b rebase-8.3 v8.3.3
# make rebase-8.3 brach as a head for working dirs
git merge -s ours openshift/master

# get diff between previous merge tag and openshift
git diff v7.5.11..openshift/master  --reverse --no-merges --ancestry-path -- ':!vendor' ':!public' > /tmp/grafana.patch

# cleanup /tmp/grafana.patch
patch -p1 < /tmp/grafana.patch

# group and commit files according to the nature of change
git add .gitgignore
git commit -s -m "UPSTREAM: <carry>: Don't ignore vendor and ui assets from git" --no-verify
...

# create PR
```

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by jan--f** [comment]
Nice work @arajkumar, thank you.
/lgtm

**Comment by arajkumar** [comment]
/hold
/retitle Bug 2038419: Bump grafana to v8.3.3

**Comment by lihongyan1** [comment]
I will work on this

**Comment by lihongyan1** [comment]
Please check, log is not correct, there is no version information and there is warn
% oc -n openshift-monitoring logs -c grafana grafana-68846784dd-5mz4t
t=2022-01-11T09:08:18+0000 lvl=info msg="The state of unified alerting is still not defined. The decision will be made during as we run the database migrations" logger=settings
t=2022-01-11T09:08:18+0000 lvl=warn msg="falling back to legacy setting of 'min_interval_seconds'; please use the configuration option in the `unified_alerting` section if Grafana 8 alerts are enabled." logger=settings
t=2022-01-11T09:08:18+0000 lvl=info msg="Config loaded from" logger=settings file=/usr/share/grafana/conf/defaults.ini
t=2022-01-11T09:08:18+0000 lvl=info msg="Config loaded from" logger=settings file=/etc/grafana/grafana.ini
t=2022-01-11T09:08:18+0000 lvl=info msg="Config overridden from command line" logger=settings arg="default.paths.data=/var/lib/grafana"

 Normal log for OCP 4.10 without PR
 % oc -n openshift-monitoring logs -c grafana grafana-5947fc4ffd-l59gn
t=2022-01-11T03:42:06+0000 lvl=info msg="Starting Grafana" logger=server version=7.5.11 commit=unknown-dev branch=master compiled=2021-11-22T09:05:11+0000
t=2022-01-11T03:42:06+0000 lvl=info msg="Config loaded from" logger=settings file=/usr/share/grafana/conf/defaults.ini
t=2022-01-11T03:42:06+0000 lvl=info msg="Config loaded from" logger=settings file=/etc/grafana/grafana.ini
t=2022-01-11T03:42:06+0000 lvl=info msg="Config overridden from command line" logger=settings arg="default.paths.data=/var/lib/grafana"

**Comment by arajkumar** [comment]
@lihongyan1 

> Please check, log is not correct, there is no version information 

Grafana starting log has been removed as part of https://github.com/grafana/grafana/commit/78596a6756b58676837731b3297488c34b71c626#diff-104a11712684e520f0affa95e6a053faeb713306a10f69ee99b9729cc9dd1996L303

> and there is warn % oc -n openshift-monitoring logs -c grafana grafana-68846784dd-5mz4t t=2022-01-11T09:08:18+0000 lvl=info msg="The state of unified alerting is still not defined. The decision will be made during as we run the database migrations" logger=settings t=2022-01-11T09:08:18+0000 lvl=warn msg="falling back to legacy setting of 'min_interval_seconds'; please use the configuration option in the `unified_alerting` section if Grafana 8 alerts are enabled." 

We don't use grafana's unified alerting, we just use it as a dashboard renderer.

**Comment by lihongyan1** [comment]
> @lihongyan1
> 
> > Please check, log is not correct, there is no version information
> 
> Grafana starting log has been removed as part of [grafana@78596a6#diff-104a11712684e520f0affa95e6a053faeb713306a10f69ee99b9729cc9dd1996L303](https://github.com/grafana/grafana/commit/78596a6756b58676837731b3297488c34b71c626#diff-104a11712684e520f0affa95e6a053faeb713306a10f69ee99b9729cc9dd1996L303)
> 
> > and there is warn % oc -n openshift-monitoring logs -c grafana grafana-68846784dd-5mz4t t=2022-01-11T09:08:18+0000 lvl=info msg="The state of unified alerting is still not defined. The decision will be made during as we run the database migrations" logger=settings t=2022-01-11T09:08:18+0000 lvl=warn msg="falling back to legacy setting of 'min_interval_seconds'; please use the configuration option in the `unified_alerting` section if Grafana 8 alerts are enabled."
> 
> We don't use grafana's unified alerting, we just use it as a dashboard renderer.

Got it, thx. I have no other comments

**Comment by lihongyan1** [comment]
> @lihongyan1
> 
> > Please check, log is not correct, there is no version information
> 
> Grafana starting log has been removed as part of [grafana@78596a6#diff-104a11712684e520f0affa95e6a053faeb713306a10f69ee99b9729cc9dd1996L303](https://github.com/grafana/grafana/commit/78596a6756b58676837731b3297488c34b71c626#diff-104a11712684e520f0affa95e6a053faeb713306a10f69ee99b9729cc9dd1996L303)
> 
> > and there is warn % oc -n openshift-monitoring logs -c grafana grafana-68846784dd-5mz4t t=2022-01-11T09:08:18+0000 lvl=info msg="The state of unified alerting is still not defined. The decision will be made during as we run the database migrations" logger=settings t=2022-01-11T09:08:18+0000 lvl=warn msg="falling back to legacy setting of 'min_interval_seconds'; please use the configuration option in the `unified_alerting` section if Grafana 8 alerts are enabled."
> 
> We don't use grafana's unified alerting, we just use it as a dashboard renderer.

Got it, thx. I have no other comments

**Pull request merged**
