### PR TITLE
remove back-ticks, replace with $()

### PR DESCRIPTION
**Pull request by jeffdyoung**
Same as https://github.com/openshift/configmap-reload/pull/6

@brancz

### CODE REVIEW

**Comment by jeffdyoung** [comment]
@brancz What can I do to get this unstuck?

**Comment by brancz** [comment]
@pgier any idea why the image build it stuck?

**Comment by sosiouxme** [comment]
/refresh
might do it? or /retest but it looks like prow just didn't pick up the result for some reason

**Comment by brancz** [comment]
Looks like that did the trick, thanks @sosiouxme !

**Pull request merged**
