### PR TITLE
OCPBUGS-21301: bump x/net to v0.17.0

### PR DESCRIPTION
**Pull request by jan--f**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Review by slashpai — COMMENTED** [review]
/lgtm

**Comment by juzhao** [comment]
@jan--f @slashpai grafana is removed since 4.11, see https://docs.openshift.com/container-platform/4.11/release_notes/ocp-4-11-release-notes.html#ocp-4-11-deprecated-removed-features, I think we can close the bug, no need to fix in 4.11

```
$ oc get clusterversion
NAME      VERSION   AVAILABLE   PROGRESSING   SINCE   STATUS
version   4.11.52   True        False         93m     Cluster version is 4.11.52
$ oc -n openshift-monitoring get pod
NAME                                                     READY   STATUS    RESTARTS   AGE
alertmanager-main-0                                      6/6     Running   0          104m
cluster-monitoring-operator-75f656f4d6-g5xmx             2/2     Running   0          119m
kube-state-metrics-758c88df9c-vpgrd                      3/3     Running   0          111m
node-exporter-6697t                                      2/2     Running   0          111m
openshift-state-metrics-67586bdfc-lt4pl                  3/3     Running   0          111m
prometheus-adapter-687d65ddfd-m4j2n                      1/1     Running   0          111m
prometheus-k8s-0                                         6/6     Running   0          109m
prometheus-operator-5fd6c44cdf-vff8v                     2/2     Running   0          111m
prometheus-operator-admission-webhook-7767b6776f-drgwd   1/1     Running   0          115m
telemeter-client-86966fc6f-ddn4z                         3/3     Running   0          111m
thanos-querier-688469ff5b-blls2                          6/6     Running   0          111m
```

**Comment by jan--f** [comment]
@juzhao iirc we do still publish 4.11 images for Grafana though. Given the nature of this fix, it might be worth fixing this.

**Pull request merged**
