### PR TITLE
Dockerfile.ocp: update to Go 1.13

### PR DESCRIPTION
**Pull request by simonpasquier**

### CODE REVIEW

**Comment by pgier** [comment]
Looks good, just wondering if the vendor updates are necessary for the Go 1.13 upgrade, or is the idea just to get the dependencies more up to date?  I think the current vendor dir is in sync with the upstream v6.4.3 tag.

**Comment by paulfantom** [comment]
This will also need a change in https://github.com/openshift/release/blob/master/ci-operator/config/openshift/grafana/openshift-grafana-master.yaml as well as file responsible for 4.4 and 4.5 releases

**Comment by simonpasquier** [comment]
> just wondering if the vendor updates are necessary for the Go 1.13 upgrade, or is the idea just to get the dependencies more up to date? I think the current vendor dir is in sync with the upstream v6.4.3 tag.

Without the vendoring update, the build fails because of an incompatible change in golang.org/x/xerrors (see golang/go/issues/34093 and https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_grafana/27/pull-ci-openshift-grafana-master-images/30/build-log.txt).

@paulfantom I'll follow up with the openshift/release updates.

**Pull request merged**
