### PR TITLE
remove piechart panels

### PR DESCRIPTION
**Pull request by paulfantom**
Piechart panels are no longer necessary as dashboards in OpenShift no longer use them.

Depends on https://github.com/openshift/cluster-monitoring-operator/pull/673
Part of https://issues.redhat.com/browse/MON-865

### CODE REVIEW

**Comment by lilic** [comment]
My PR was merged in CMO.

**Comment by lilic** [comment]
> level=error msg="Cluster operator monitoring Degraded is True with UpdatingGrafanaFailed: Failed to rollout the stack. Error: running task Updating Grafana failed: reconciling Grafana Deployment failed: updating deployment object failed: waiting for DeploymentRollout of grafana: deployment grafana is not ready. status: (replicas: 2, updated: 1, ready: 0, unavailable: 2)"

/hold

**Comment by paulfantom** [comment]
There was one more reference to piechart plugin left. I removed it and now it should work fine.

/unhold

**Comment by lilic** [comment]
/retest

weird stuff :D

**Pull request merged**
