### PR TITLE
Bug 1768492: fix v6.4.3 upgrade

### PR DESCRIPTION
**Pull request by pgier**
The reason the previous build wasn't working is because the old Dockerfile was expecting the front-end code to be pre-generated and committed to git.  I tried to generate front-end code in Docker but this seems to be problematic due to some dependencies not packaged for openshift.

This update also brings the Dockerfile.ocp to be more similar to upstream.
Regenerated frontend code to the git repo and add some notes in an openshift readme.

### CODE REVIEW

**Comment by s-urbaniak** [comment]
judging from the build output it tries to fetch things from the internet which does not succeed:
```
error: build error: failed to pull image: repository docker.io/0 not found: does not exist or no pull access
```

**Comment by pgier** [comment]
This is mostly the same as the previous commit, just rebased against current master, and organized the commits a bit better to separate (1) upstream sources, (2) openshift specific files, and (3) generated front-end code.

The build failure was due to the `COPY --from=0` directive used to copy files from the builder image.  This needed to be changed to use the specific builder image naem `COPY --from=builder`.  Likely due to a different version of docker used for openshift builds.

**Comment by pgier** [comment]
@s-urbaniak @simonpasquier You guys ok with this?

**Comment by pgier** [comment]
Tested this in an openshift cluster and it seems that the grafana upgrade did not solve the issue with the missing pie chart plugin.  I'm not sure how this was working previously.  I have added a commit which automatically adds the piechart plugin when the container starts up, and I'll test this shortly.

**Comment by pgier** [comment]
The pie chart seems to be working fine now, should be good to merge.

**Comment by s-urbaniak** [comment]
@pgier thanks a lot! :+1:

**Pull request merged**
