### PR TITLE
[WIP] OCPBUGS-14805: Bump Grafana to v8.5.27

### PR DESCRIPTION
**Pull request by jan--f**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by jan--f** [comment]
The go test fail on two places:
```
=== RUN   TestRecoveryMiddleware/Given_an_API_route_that_panics/recovery_middleware_should_return_JSON
    recovery_test.go:22: Decoded JSON json map[error:Server Error - /go/src/github.com/openshift/grafana/pkg/middleware/recovery_test.go:45 (0x11f7b66)
        	panicHandler: panic("Handler has panicked")
        /go/src/github.com/openshift/grafana/pkg/middleware/recovery_test.go:78 (0x11f8381)
        	recoveryScenario.func1.1: sc.handlerFunc(sc.context)
        /usr/lib/golang/src/reflect/value.go:556 (0x4d6a04)
        	Value.call: call(frametype, fn, stackArgs, uint32(frametype.size), uint32(abi.retOffset), uint32(frameSize), &regArgs)
        /usr/lib/golang/src/reflect/value.go:339 (0x4d5f84)
        	Value.Call: return v.call("Call", in)
        /go/src/github.com/openshift/grafana/pkg/web/inject.go:159 (0xc86da6)
        	(*injector).callInvoke: return reflect.ValueOf(f).Call(in), nil
        /go/src/github.com/openshift/grafana/pkg/web/inject.go:119 (0xc869f4)
        	(*injector).Invoke: return inj.callInvoke(f, t, t.NumIn())
        /go/src/github.com/openshift/grafana/pkg/web/context.go:67 (0xc85ceb)
        	(*Context).run: if _, err := ctx.Invoke(ctx.handler()); err != nil {
        /go/src/github.com/openshift/grafana/pkg/web/context.go:62 (0xc8dbfa)
        	(*Context).Next: ctx.run()
        /go/src/github.com/openshift/grafana/pkg/web/macaron.go:155 (0xc8dbec)
        	(*Macaron).UseMiddleware.func1: c.Next()
        /usr/lib/golang/src/net/http/server.go:2047 (0x6e23ee)
        	HandlerFunc.ServeHTTP: f(w, r)
        /go/src/github.com/openshift/grafana/pkg/web/render.go:44 (0xc889a6)
        	Renderer.func1.1: next.ServeHTTP(rw, req)
        /usr/lib/golang/src/reflect/value.go:556 (0x4d6a04)
        	Value.call: call(frametype, fn, stackArgs, uint32(frametype.size), uint32(abi.retOffset), uint32(frameSize), &regArgs)
        /usr/lib/golang/src/reflect/value.go:339 (0x4d5f84)
        	Value.Call: return v.call("Call", in)
        /go/src/github.com/openshift/grafana/pkg/web/inject.go:159 (0xc86da6)
        	(*injector).callInvoke: return reflect.ValueOf(f).Call(in), nil
        /go/src/github.com/openshift/grafana/pkg/web/inject.go:119 (0xc869f4)
        	(*injector).Invoke: return inj.callInvoke(f, t, t.NumIn())
        /go/src/github.com/openshift/grafana/pkg/web/context.go:67 (0xc85ceb)
        	(*Context).run: if _, err := ctx.Invoke(ctx.handler()); err != nil {
        /go/src/github.com/openshift/grafana/pkg/web/context.go:62 (0x11f05aa)
        	(*Context).Next: ctx.run()
        /go/src/github.com/openshift/grafana/pkg/middleware/recovery.go:168 (0x11f05a1)
        	Recovery.func1: c.Next()
        /go/src/github.com/openshift/grafana/pkg/web/context.go:32 (0xc85bdb)
        	ContextInvoker.Invoke: invoke(params[0].(*Context))
        /go/src/github.com/openshift/grafana/pkg/web/inject.go:139 (0xc86b14)
        	(*injector).fastInvoke: return f.Invoke(in)
        /go/src/github.com/openshift/grafana/pkg/web/inject.go:117 (0xc86a3c)
        	(*injector).Invoke: return inj.fastInvoke(v, t, t.NumIn())
        /go/src/github.com/openshift/grafana/pkg/web/context.go:67 (0xc85ceb)
        	(*Context).run: if _, err := ctx.Invoke(ctx.handler()); err != nil {
        /go/src/github.com/openshift/grafana/pkg/web/router.go:156 (0xc8a21d)
        	(*Router).Handle.func1: c.run()
        /go/src/github.com/openshift/grafana/pkg/web/router.go:213 (0xc8aed5)
        	(*Router).ServeHTTP: leaf.handle(rw, req, nil)
        /go/src/github.com/openshift/grafana/pkg/web/macaron.go:189 (0xc882f0)
        	(*Macaron).ServeHTTP: m.Router.ServeHTTP(rw, req)
        /go/src/github.com/openshift/grafana/pkg/middleware/testing.go:121 (0x11f1bb1)
        	(*scenarioContext).exec: sc.m.ServeHTTP(sc.resp, sc.req)
        /go/src/github.com/openshift/grafana/pkg/middleware/recovery_test.go:22 (0x1203236)
        	TestRecoveryMiddleware.func1.1: sc.fakeReq("GET", apiURL).exec()
        /go/src/github.com/openshift/grafana/pkg/middleware/recovery_test.go:84 (0x11f8302)
        	recoveryScenario.func1: fn(t, sc)
        /usr/lib/golang/src/testing/testing.go:1259 (0x517721)
        	tRunner: fn(t)
        /usr/lib/golang/src/runtime/asm_amd64.s:1581 (0x475fa0)
        	goexit: BYTE	$0x90	// NOP
         message:Internal Server Error - Check the Grafana server logs for the detailed error message.]
```
and 
```
=== RUN   TestListFiles
2023/07/04 13:05:19 golden file updated: testdata/public_testdata.golden.txt
    service_test.go:37: 
        	Error Trace:	/go/src/github.com/openshift/grafana/pkg/services/store/service_test.go:37
        	Error:      	Received unexpected error:
        	            	frame[0] mismatch (-want +got):
        	            	  &data.Frame{
        	            	  	Name: "",
        	            	  	Fields: []*data.Field{
        	            	  		&{Name: "name", vector: &data.stringVector{"browser_marketshare.csv", "flight_info_by_state.csv", "gdp_per_capita.csv", "js_libraries.csv", ...}},
        	            	- 		&{
        	            	- 			Name: "mediaType",
        	            	- 			vector: &data.stringVector{
        	            	- 				"text/csv; charset=utf-8", "text/csv; charset=utf-8",
        	            	- 				"text/csv; charset=utf-8", "text/csv; charset=utf-8",
        	            	- 				"text/csv; charset=utf-8", "text/csv; charset=utf-8",
        	            	- 				"text/csv; charset=utf-8",
        	            	- 			},
        	            	- 		},
        	            	+ 		&{
        	            	+ 			Name: "mediaType",
        	            	+ 			vector: &data.stringVector{
        	            	+ 				"application/octet-stream", "application/octet-stream",
        	            	+ 				"application/octet-stream", "application/octet-stream",
        	            	+ 				"application/octet-stream", "application/octet-stream",
        	            	+ 				"application/octet-stream",
        	            	+ 			},
        	            	+ 		},
        	            	  		&{Name: "size", Config: &{Unit: "bytes"}, vector: &data.int64Vector{355, 681, 4116, 179, ...}},
        	            	  	},
        	            	  	RefID: "",
        	            	  	Meta:  &{Type: "directory-listing", Custom: map[string]any{...}},
        	            	  }
        	            	
        	Test:       	TestListFiles
--- FAIL: TestListFiles (0.01s)
```
They are potentially related but I fail to reproduce this locally with go1.17 (or a newer version).

**Comment by simonpasquier** [comment]
I've downloaded the upstream 8.5.27 binary and it's been built with go1.19.9 :thinking:

**Pull request closed without merging**
