### PR TITLE
Bug 1851251: Bump jQuery to 3.5.1

### PR DESCRIPTION
**Pull request by simonpasquier**
Backport of https://github.com/grafana/grafana/pull/25651

### CODE REVIEW

**Comment by simonpasquier** [comment]
cc @openshift/openshift-team-monitoring

**Comment by simonpasquier** [comment]
The changes are not yet released upstream (see https://github.com/grafana/grafana/commit/e2ba0731e284f7fe524c6dec2686594d6248daa5). They should be available in a future 7.x release but not 6.x.

**Comment by paulfantom** [comment]
/lgtm

Holding as there were some discussions on slack about this PR
/hold

**Comment by lilic** [comment]
> The changes are not yet released upstream

@simonpasquier seems like those changes are in 7.0.4 release here, no? -> https://github.com/grafana/grafana/blob/v7.0.4/package.json

**Comment by simonpasquier** [comment]
@lilic yes I was mistaken because the master changes had been cherry-picked to the release branch and looking at the original PR, it only showed it in `master`. I'm looking at what it takes to bump to 7.x...

**Comment by simonpasquier** [comment]
/close

in favor of #40

**Pull request closed without merging**
