### PR TITLE
add VERSION file

### PR DESCRIPTION
**Pull request by raptorsun**
This PR adds a version file to be consistent with other openshift forks, especially those in the monitoring stack. 

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by arajkumar** [comment]
How about the naive approach of fall back to package.json on VERSION download failure from cmo?

```
diff --git a/hack/generate-versions.sh b/hack/generate-versions.sh
index 33c4d19d..1b4f526e 100755
--- a/hack/generate-versions.sh
+++ b/hack/generate-versions.sh
@@ -20,7 +20,7 @@ PATH="${TMP_BIN}:${PATH}"
 : "${INTERACTIVE:=true}"

 version_from_remote() {
-       curl --retry 5 --silent --fail "https://raw.githubusercontent.com/${1}/master/VERSION"
+       curl --retry 5 --silent --fail "https://raw.githubusercontent.com/${1}/master/VERSION" || curl --retry 5 --silent --fail "https://raw.githubusercontent.com/${1}/master/package.json" | jq -r '.version'
 }
```

**Comment by raptorsun** [comment]
> How about the naive approach of fall back to package.json on VERSION download failure from cmo?
> 
> ```
> diff --git a/hack/generate-versions.sh b/hack/generate-versions.sh
> index 33c4d19d..1b4f526e 100755
> --- a/hack/generate-versions.sh
> +++ b/hack/generate-versions.sh
> @@ -20,7 +20,7 @@ PATH="${TMP_BIN}:${PATH}"
>  : "${INTERACTIVE:=true}"
> 
>  version_from_remote() {
> -       curl --retry 5 --silent --fail "https://raw.githubusercontent.com/${1}/master/VERSION"
> +       curl --retry 5 --silent --fail "https://raw.githubusercontent.com/${1}/master/VERSION" || curl --retry 5 --silent --fail "https://raw.githubusercontent.com/${1}/master/package.json" | jq -r '.version'
>  }
> ```

This is good idea, too. I prefer to standardize every fork repositories with a version file so that we will not have exceptions to manage.
Anyway, I will modify the generate-versions.sh script, too. So we will have the versions.yaml file correctly generated in CMO regardless of which way we choose :)

**Comment by arajkumar** [comment]
IMHO, we might miss updating `VERSION` file if it has to be done manually.

**Comment by arajkumar** [comment]
@raptorsun Unrelated, but please fix OWNERS file :)

**Comment by raptorsun** [comment]
> IMHO, we might miss updating `VERSION` file if it has to be done manually.

hmm, it will be nice to update version file automatically. I need to check if github has some tool to facilitate this operation.

**Comment by raptorsun** [comment]
> @raptorsun Unrelated, but please fix OWNERS file :)

of course, I will put the change in another PR :)

**Comment by raptorsun** [comment]
https://github.com/openshift/cluster-monitoring-operator/pull/1485

I put your change to CMO, now. thanks ^^ @arajkumar

**Comment by simonpasquier** [comment]
If we add a VERSION file, I agree that we need to ensure that it needs to be kept in sync with the package.json's version.

**Pull request closed without merging**
